# Generated by Django 3.2.4 on 2021-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_productcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state_active',
            field=models.BooleanField(default=True),
        ),
    ]
